export const SUCCESS_GET_PRODUCTS = 'SUCCESS_GET_PRODUCTS'

//State of order
export const SELECT_PRODUCT = 'SELECT_PRODUCT'
export const CONFIRM_ORDER_DISH = 'CONFIRM_ORDER_DISH'
export const SHOW_SUMARRY = 'SHOW_SUMARRY'